### ISSUE TITLE
NativeScript 4.1 with Angular: Modal view with navigation may result in router issues so some pages can no longer be shown

### ISSUE THREAD

**Issue by joemundo** [NativeScript/nativescript-sdk-examples-ng#283]
Can you please provide some help on the following issue?

I am very happy to see that navigation in modal views is now supported by NativeScript 4.1 with Angular as well but I recognised the following issue in the example given, so I fear that navigation with in modal views may not yet correctly working in NativeScript 4.1 (or if you could show me some better example than this I would be very glad :) )
I would be really nice if you could help to solve this issue since it is currently a show stopper of my project.
It seems the issue does not exist with NativeScript Core (4.0 / 4.1)

How to reproduce:
1. ensure NativeScript 4.1 is installed
2. clone example and run it in iPhone or iPhone Simulator
```
git clone https://github.com/NativeScript/nativescript-sdk-examples-ng
cd nativescript-sdk-examples-ng/
tns run ios --emulator
```
2. List "NativeScript Code Samples" will be shown
3. scroll down to row "Modal page" and tap it -> page "Modal page" will be shown
4. tap row "Modal page navigation" -> page "Modal page navigation" will be shown
5. tap button "SHOW MODAL" -> page "MODAL VIEW" will be presented as a modal view sliding in from bottom
6. tap button "Next page" -> page "Second Modal Page" will be shown
7. tap button "CLOSE MODAL" -> modal view will disappear by sliding back to bottom and page "Modal page navigation" will become visible again
8. tap back button in left top corner -> page "Modal page navigation" disappears to the right and page "Modal page" becomes visible again **and the following error is logged in the terminal:** but it is expected that this error does not appear.

```
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:1590:24: ERROR Error: Uncaught (in promise): Error: Currently in page back navigation - component should be reattached instead of activated.
activateWith@file:///app/tns_modules/nativescript-angular/router/page-router-outlet.js:212:28 [angular]
activateRoutes@file:///app/tns_modules/@angular/router/bundles/router.umd.js:4269:52 [angular]
file:///app/tns_modules/@angular/router/bundles/router.umd.js:4221:33 [angular]
forEach@[native code] [angular]
activateChildRoutes@file:///app/tns_modules/@angular/router/bundles/router.umd.js:4220:36 [angular]
activateRoutes@file:///app/tns_modules/@angular/router/bundles/router.umd.js:4241:41 [angular]
file:///app/tns_modules/@angular/router/bundles/router.umd.js:4221:33 [angular]
forEach@[native code] [angular]
activateChildRoutes@file:///app/tns_modules/@angular/router/bundles/router.umd.js:4220:36 [angular]
activate@file:///app/tns_modules/@angular/router/bundles/router.umd.js:4142:33 [angular]
fil
```

9. Tap any row e.g. "Modal page navigation" -> it is expected that e.g. page "Modal page navigation" would be shown again, **but the UI does not change**. Instead if e.g. tapping row "Modal page example" the following same error as above is logged on terminal again.

So it seems the router does no longer work.

Workaround:
In file nativescript-sdk-examples-ng/app/modal-page/modal-page-navigation/second-modal-view-content.component.ts replace 

```
    onClose(): void {
        this._params.closeCallback("return value");
    }
```

with

```
    onClose(): void {
        this.router.back();
        setTimeout(() => {
            this._params.closeCallback("return value");
        }, 1000);
    }
```

The workaround will first go back by one page in the modal view and then dismiss the modal view. Due to waiting for 1 second the user can see this behaviour which is not desired. Without waiting long enough the workaround would not work (e.g. 100ms seems not enough).

Many thanks for your help!

**Comment by tsonevn** [comment]
HI @joemundo,
Excuse me for the delay in reply.
Can you check whether you will be able to recreate the issue with the latest  NativeScript modules `4.2` and nativescript-angular `6.1.0`?

**Comment by NickIliev** [comment]
Closing the issue as not reproducible with latest and due to inactivity.
